---
- name: installing software packages
  hosts: all
  tasks: 
   - name: install software packages
     apt:
      name: "{{item}}"
      state: absent
      update_cache: yes
     with_items:
      - tree
      - apache2
      - git
      - openjdk-8-jdk
...
